### ISSUE TITLE
Unable to use tracking.py in mini_marker_tracking 

### ISSUE THREAD

**Issue by Yuengkingto** [gelsightinc/gsrobotics#11]
I'm happy to be a user of Gelsight. But I ran tracking.py in mini_marker_tracking, it said : 
File "tracking.py", line 62, in resize_crop_mini
    img = cv2.resize(img, (895, 672))  # size suggested by janos to maintain aspect ratio
cv2.error: OpenCV(3.4.17) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
     Differently, when I ran another tracking.py in mini_tracking_windows,it could show frame and mark.But, there are some strange red lines in the frame that are glowing in all directions from the top left corner:
Can you get me some help. I run those demos in win10,python 3.8.15

**Comment by debrashure** [comment]
The marker tracking demos have been refactored.  The code you are using now has been moved to the mini_tracking_windows_V0.  That code uses a setting.py file which has the inputs N and M, the row and column of the marker array.  If you get those red lines in all directions, it usually means that you have the wrong values for N and M.  Try counting the number of dots you have and make sure they are set in setting.py

` 
N_ = 8
M_ = 10
`
There are also some new demos you can try in demos/marker_tracking that need no inputs.  Please see 

[demos/marker_tracking/mean_shift_marker_tracking.py](https://github.com/gelsightinc/gsrobotics/blob/main/demos/marker_tracking/mean_shift_marker_tracking.py)

and

[demos/marker_tracking/optical_flow_marker_tracking.py](https://github.com/gelsightinc/gsrobotics/blob/main/demos/marker_tracking/optical_flow_marker_tracking.py)

**Comment by 888yzh999** [comment]
demos/mini_tracking_windows_V0/tracking.py里的find_marker包怎么下载
ModuleNotFoundError: No module named 'find_marker'

**Comment by Joao8bit** [comment]
@debrashure 
demos/mini_tracking_windows_V0/tracking.py gives the following error:
ModuleNotFoundError: No module named 'find_marker'
