### ISSUE TITLE
Use get_image instead of get_raw_image in the while loop

### ISSUE THREAD

**Issue by duyipai** [gelsightinc/gsrobotics#14]
The current implementation of optical_flow_marker_tracking.py and mean_shift_marker_tracking.py are using get_raw_image to grab gelsight mini images, which is causing significant delay since it flushes out the first 10 images. Using get_image in the while-loop would fix the problem.

**Comment by debrashure** [comment]
Thanks for pointing this out.  The code has been cleaned up and the problem is fixed.
