### ISSUE TITLE
Unable to run "show3d.py"

### ISSUE THREAD

**Issue by echo19990722andy** [gelsightinc/gsrobotics#3]
I have the same issue as the closed issued about running "show3d.py"
I am using Ubuntu-20-04 in VMware Workstation and the python is version 3.8.10
My Gelsight device is GelSight Mini
But I find the problem(as mentioned in the former issue):

gs3drecon.py, line 13, in <module>
from gelsightcore import poisson_reconstruct
ImportError: cannot import name 'poisson_reconstruct' from 'gelsightcore' (unknown location)

Any ideas~? Or the issue is relate to the VMware Workstation?

**Comment by CarlDegio** [comment]
Same issue, Ubuntu20 and Python3.8.15.

**Comment by CarlDegio** [comment]
environment variable should be set

**Comment by Shimly-2** [comment]
I have the same issue using Ubuntu-18-04 in VMware Workstation and the python version is 3.6.9. 
How to set the environment variable to make it work？

**Comment by echo19990722andy** [comment]
I directly add the Gelsight and GelsightCore paths in the setup.sh file to the .bashrc file of the Ubuntu System.
Using   sudo gedit .bashrc   to add two paths in the bashrc file.
Make sure that you run all the commands in the preparing stages exactly as the README file in the gsrobotics folder, don't miss any of them.

----- 原始邮件 -----
发件人: "HHH" ***@***.***>
收件人: "gelsightinc/gsrobotics" ***@***.***>
抄送: "gongyuru" ***@***.***>, "Author" ***@***.***>
发送时间: 星期一, 2022年 12 月 05日 下午 6:01:39
主题: Re: [gelsightinc/gsrobotics] Unable to run "show3d.py" (Issue #3)

I have the same issue using Ubuntu-18-04 in VMware Workstation and the python version is 3.6.9. 

How to set the environment variable to make it work？

**Comment by echo19990722andy** [comment]
It works! Thanks so much

----- 原始邮件 -----
发件人: "Zihao Liu" ***@***.***>
收件人: "gelsightinc/gsrobotics" ***@***.***>
抄送: "gongyuru" ***@***.***>, "Author" ***@***.***>
发送时间: 星期二, 2022年 12 月 06日 下午 6:41:43
主题: Re: [gelsightinc/gsrobotics] Unable to run "show3d.py" (Issue #3)

> I have the same issue using Ubuntu-18-04 in VMware Workstation and the python version is 3.6.9. How to set the environment variable to make it work？



In readme:

```

PYDIR=`pip3 show gelsight | grep -i location | cut -f2 -d" "`

export LD_LIBRARY_PATH=$PYDIR/gelsightcore:$LD_LIBRARY_PATH

export PYTHONPATH=$PYDIR/gelsightcore:$PYDIR/gelsight:$PYTHONPATH

```

add in bashrc or manual set
