### ISSUE TITLE
Camera id about gelsight mini

### ISSUE THREAD

**Issue by CarlDegio** [gelsightinc/gsrobotics#5]
I got confused about when I connect the gelsight mini, two video id appear in /dev. Such as /dev/video0 and /dev/video1. But in fact, there should be one video? Or the inner camera has two view.
I read README but didn't found information about this.

**Comment by debrashure** [comment]
You are correct, v4l2-ctl --list-devices will list all the /dev/video* for a single device.
You can use the first /dev/video# listed for the device.  The first one is for Video Capture and the second one is for Metadata
