### ISSUE TITLE
[Feature request] Reduce stream resolution to achieve max fps

### ISSUE THREAD

**Issue by joaromi** [gelsightinc/gsrobotics#6]
Hello, the sensor datasheet shows that the maximum framerate for the GelSight Mini sensor is 25fps. However, I only get around 15fps in my computer. Using the Digit sensor and the same code I obtain 30fps. I believe that being able to reduce the size of the streamed images directly in the sensor would increase these values (Digit libraries already have this feature).

**Comment by debrashure** [comment]
joaromi,
Thank you so much for the feedback.  We have added the request to our feature request backlog.
Much appreciated,
Debbie

**Comment by duyipai** [comment]
> Hello, the sensor datasheet shows that the maximum framerate for the GelSight Mini sensor is 25fps. However, I only get around 15fps in my computer. Using the Digit sensor and the same code I obtain 30fps. I believe that being able to reduce the size of the streamed images directly in the sensor would increase these values (Digit libraries already have this feature).

I am having similar problem on my Ubuntu20 computer. I found it was because on Linux OpenCV used v4l2 backend to capture the stream and it was slower than MSMF, the default one on Windows. I tested on both OS. On Windows it gets 25FPS but on Ubuntu it is only 18FPS at most. Hope this problem can be fixed.

**Comment by duyipai** [comment]
Dear GelSight developer,
I am grateful to see the new frame rate example with recent commits. However, I will always get a printout around 24~25 from that example, but the actual frame rate is only around 18FPS. I think the current frame rate example is not calculating the correct one. Would you please fix it and see if the frame rate can be increased to 25FPS on Ubuntu? Thank you.

**Comment by Mingrui-Yu** [comment]
I am facing the same issue as @duyipai .

**Comment by luoshaqi** [comment]
I am facing the same issue
